In [1]:
#Corr. trial
import numpy as np
from sklearn.neighbors import KDTree
from correlation_package import *

In [9]:
import numpy as np
from sklearn.neighbors import KDTree

# Tiny 3x3 grid
# 0 = phenotype A, 1 = phenotype B
A = np.array([
    [0, 1, 2],
    [1, 0, 1],
    [2, 1, 2]
])

N = 3         # number of phenotypes
radius = 1.5 # neighborhood radius (covers adjacent cells)
A_series = [A]  # just one snapshot for simplicity


In [10]:
total, avg = counts_matrix(A, N, radius)
corr_matrix = correlation_matrix_for_snapshot_unordered(A,N, radius, global_normalization=True)

In [11]:
print("total pairs:\n", total.sum())
print("Original Matrix:\n", A)
print("Total neighbor counts (unordered):\n", total)
print("Average neighbors per site:\n", avg)
print("Correlation matrix:\n", corr_matrix)

total pairs:
 16.0
Original Matrix:
 [[0 1 2]
 [1 0 1]
 [2 1 2]]
Total neighbor counts (unordered):
 [[4. 6. 0.]
 [6. 0. 0.]
 [0. 0. 0.]]
Average neighbors per site:
 [[2.  1.5 0. ]
 [2.  0.  0. ]
 [nan nan nan]]
Correlation matrix:
 [[0.29166667 0.58333333        nan]
 [0.58333333 0.                nan]
 [       nan        nan        nan]]
