In [5]:
#Corr. trial
import numpy as np
from sklearn.neighbors import KDTree
from correlation_package import *

In [17]:
import numpy as np
from sklearn.neighbors import KDTree

# Tiny 3x3 grid
# 0 = phenotype A, 1 = phenotype B
A = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 1]
])

N = 2          # number of phenotypes
radius = 1.5   # neighborhood radius (covers adjacent cells)
A_series = [A]  # just one snapshot for simplicity


In [18]:
total, avg = counts_matrix_for_snapshot_unordered(A, N, radius)
corr_matrix = correlation_matrix_for_snapshot_unordered(A,N, radius, global_normalization=True)

In [19]:
print("total pairs:\n", total.sum())
print("Original Matrix:\n", A)
print("Total neighbor counts (unordered):\n", total)
print("Average neighbors per site:\n", avg)
print("Correlation matrix:\n", corr_matrix)

total pairs:
 32.0
Original Matrix:
 [[0 0 1]
 [1 0 0]
 [0 1 1]]
Total neighbor counts (unordered):
 [[ 6. 12.]
 [12.  2.]]
Average neighbors per site:
 [[2.4 2.4]
 [3.  1. ]]
Correlation matrix:
 [[0.27     0.675   ]
 [0.675    0.140625]]
